### ISSUE TITLE
PHP times out, making setup unusable on slower devices

### ISSUE THREAD

**Issue by toblie** [Forceu/partkeepr_docker#1] opened 2020-11-25 12:16 UTC
Hi,
badly I am not able to setup the server.
While the the step 'warming up the cache' it always throws an error and I am not able to finish the setup.
Error message:
![Screenshot_20201125-131520_Chrome](https://user-images.githubusercontent.com/3874207/100226648-5109fc80-2f20-11eb-8c98-536cee17df2e.jpg)

Its running on pine64 using Portainer.
Maybe anyone can help?

Thx

**Comment by Forceu** [comment] 2020-11-25 12:36
Thanks, it seems that PHP times out. I changed the maximum execution time in 1d22aa36b2c60f6bbf274d441836089869166972, the new image is up now. Let me know in case it is not working for you!

**Comment by toblie** [comment] 2020-11-25 15:38
> the new image is up now.

Thanks for your fast reply!
So if I use the image f0rc3/partkeepr:arm64v8-latest from docker.io it should be already the newest?
THX

**Comment by Forceu** [comment] 2020-11-25 15:40
Yes, that should work :)

**Comment by toblie** [comment] 2020-11-25 16:00
Badly again not working but with other error:
<img width="596" alt="Bildschirmfoto 2020-11-25 um 16 59 45" src="https://user-images.githubusercontent.com/3874207/100251962-a4d80e00-2f3f-11eb-9690-84e2dcd5000c.png">
<img width="592" alt="Bildschirmfoto 2020-11-25 um 16 56 50" src="https://user-images.githubusercontent.com/3874207/100251747-64789000-2f3f-11eb-969e-c53549ddad97.png">
<img width="553" alt="Bildschirmfoto 2020-11-25 um 16 58 35" src="https://user-images.githubusercontent.com/3874207/100251829-7e19d780-2f3f-11eb-995c-805124ec5655.png">

I would paste the whole error, but the error windows prevents to select and copy the text...
Any further idea?

THX

**Comment by Forceu** [comment] 2020-11-25 16:09
Okay that is interesting... can you please go execute

`docker exec -i partkeepr-web chmod 777 -R /app/app/cache/`

and let me know if that is working for you

**Comment by toblie** [comment] 2020-11-25 16:16
No, the same error after chmod.

**Comment by Forceu** [comment] 2020-11-25 16:26
Did that happen during or after the setup?

**Comment by toblie** [comment] 2020-11-25 16:29
on the same step with warming the cache.

**Comment by Forceu** [comment] 2020-11-25 16:35
Hm weird. Can you please try with the image `f0rc3/partkeepr:multiarch-latest` if the same problem happens there as well?

**Comment by toblie** [comment] 2020-11-25 16:48
It seems this image is not available:
Failure
No such image: f0rc3/partkeepr:multiarch-latest
... ok now its pulled, don't know where was the issue here.
Just testing and then come back.

**Comment by toblie** [comment] 2020-11-25 17:52
Well... same error with this image. 
Before I set a memory limit to 1GB and CPU usage to 1 for this container. Now I set both to unlimited, but same this way...
Not sure if it has anything todo with this even its only a warning? All other steps are green.
<img width="892" alt="Bildschirmfoto 2020-11-25 um 18 43 38" src="https://user-images.githubusercontent.com/3874207/100263727-2a62ba80-2f4e-11eb-9659-a1971af02f2b.png">

Maybe there is any log which can help you?

**Comment by Forceu** [comment] 2020-11-26 11:35
I just saw your issue https://github.com/partkeepr/PartKeepr/issues/1160

I think it might be related to this image, not Partkeepr. Did you import any data? If not, please try the following:

`docker run -p 127.0.0.1:7156:80 --name partkeepr-web-test -d f0rc3/partkeepr:multiarch-latest`

Then open `localhost:7156` (different port) and try the setup again. To get the authkey, execute 

`docker exec -it partkeepr-web-test cat /app/app/authkey.php `

This does not mount any volumes, which I assume is the issue here...


Also I tried reproducing the issue on a VM running docker instead of podman, unfortunately I cannot reproduce the problem :/

**Comment by toblie** [comment] 2020-11-26 12:27
Sorry I thougt maybe the issue is on partkeepr not your image.
Its still not working, but now it shows only invalid server response on the same step without any details:
<img width="655" alt="Bildschirmfoto 2020-11-26 um 13 23 45" src="https://user-images.githubusercontent.com/3874207/100350839-cb9f4e80-2fea-11eb-9711-ae13bf21c45c.png">

I tried it twice... with same result.

**Comment by Forceu** [comment] 2020-12-01 14:35
I rewrote the Dockerfile to be now based on nginx, can you please try again with `f0rc3/partkeepr:multiarch-latest`?

**Comment by toblie** [comment] 2020-12-02 06:51
Hi, thx for rewrite.
I already checked it, but now with nginx it still hangs on the same step. But this time it shows an error 504:
<img width="933" alt="Bildschirmfoto 2020-12-02 um 07 50 05" src="https://user-images.githubusercontent.com/3874207/100838657-2285a780-3473-11eb-9f58-487f6281f407.png">

I tried it just simple like your last request, without volumes.

**Comment by Forceu** [comment] 2020-12-02 12:03
Thanks, we're getting there! Apparently the server needed too much time, therefore a timeout was raised (and that was the reason why I was not able to reproduce the problem). I pushed an updated image, let me know if it is working now!

**Comment by toblie** [comment] 2020-12-02 12:24
Hi, this image won't run. It stops some seconds after start. The log show this error:
`standard_init_linux.go:211: exec user process caused "exec format error"
`

**Comment by Forceu** [comment] 2020-12-02 13:31
Apparently the automatic docker builder was misconfigured, the image should (finally) work now.

**Comment by toblie** [comment] 2020-12-03 07:27
Same error 504 again...

**Comment by Forceu** [comment] 2020-12-03 12:21
Oh I missed one line in the nginx config. Now it should _really_ work :D

**Comment by toblie** [comment] 2020-12-03 13:34
badly not really :-(
<img width="928" alt="Bildschirmfoto 2020-12-03 um 14 30 29" src="https://user-images.githubusercontent.com/3874207/101024391-55fc2b00-3574-11eb-8995-e38558369bad.png">

**Comment by Forceu** [comment] 2020-12-03 18:49
Thanks, I was able to reproduce the problem with CPU throttling. I am still a bit confused however why this happens... Nginx, PHP and PHP-FPM are all set to run for 50 minutes max. This issue will need more investigating, unfortunately at the moment I am unable to find the issue...

**Comment by toblie** [comment] 2020-12-03 18:51
Maybe its possible to disable the cache or at least warming the cache? Or maybe enable the PHP APCu cache module ?
I am not sure its because on the device performance, because other php based images runs without any issue.

But anyway thanks for your time!

**Comment by Forceu** [comment] 2020-12-03 19:11
I assume you are not running the container through a reverse proxy or any other proxy? If not, it might be related to https://github.com/partkeepr/PartKeepr/issues/811
You could also try to run `php /app/app/console cache:warmup` on the container, maybe that helps?

**Comment by toblie** [comment] 2020-12-03 19:57
No there is no proxy in my setup...
But after warming the cache from shell, I can run partkeepr :-)
Is there any important step in setup which should be after warming up step which is missing now ?

**Comment by Forceu** [comment] 2020-12-03 20:02
Great to hear! I am not 100% sure, but it should work now without any problems.
I will close this issue, as I think it is rather related to Partkeepr itself and add instructions to the readme file.

**Closed as completed by Forceu** 2020-12-03 20:02 UTC
Labels: bug, help wanted

**Comment by toblie** [comment] 2020-12-03 20:17
Yes that's really curious, because using the console it needs less than 20s to finish the task.

Thanks for your help and great evening!

**Comment by toblie** [comment] 2020-12-04 05:32
@Forceu 
Can you maybe help me one last time?
Is it possible for you to add the installation of apcu extension and php config within your image?
Maybe this is the best solution, because I found following in the partkeepr wiki:

```
In order to achieve best performance, you should ensure that:

- Ensure your max_execution_time is set to 120 seconds or higher, this is required for the setup.

- Opcache enabled

- PHP-APCu installed and enabled with both cache.dunglas and cache.doctrine

```
https://wiki.partkeepr.org/wiki/APC_Metadata_Caching

If you have some time, would be great if you can add an image for testing...
THX
